name: Test
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm dependencies
        run: npm install
      - name: Run JS linter
        run: npm run lint
